import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Text, Heading, Button, Box, Flex } from "@chakra-ui/react";
import { ArrowForwardIcon } from "@chakra-ui/icons";
import { useEffect } from "react";

export default function Summary(props) {
  
  var actual = JSON.parse(atob(props.cont));
  console.log(actual);
  return (
    <Box>
      <Head>
        <title>Summary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        flexDirection="row"
        justifyContent="center"
        alignItems="center"
        marginBottom={10}
      >
        <Box>
          <Heading as="h3">Summary of items</Heading>
          {console.log("this")}
          {console.log(actual)}
          {actual.map((prop) => (
            <div>
              <strong>{prop.itemname}</strong>
              <p>{prop.address}</p>
              <p>{prop.latitude}</p>
              <p>{prop.longitude}</p>
            </div>
          ))}
        </Box>
      </Flex>
    </Box>
  );
}
export async function getServerSideProps(context) {
  console.log(context.query.code);
  return {
    props: { cont: context.query.code }, // will be passed to the page component as props
  };
}