# Generated by Django 3.2 on 2022-01-06 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('question', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallForCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_method', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=1000, null=True)),
                ('website', models.CharField(blank=True, max_length=1000, null=True)),
                ('minimum_weight', models.CharField(blank=True, max_length=1000, null=True)),
                ('pricing_terms', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='g',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('suggestion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(max_length=255)),
                ('bluebinrecyclable', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('call_for_collection', models.CharField(blank=True, max_length=1000, null=True)),
                ('in_good_condition', models.CharField(blank=True, max_length=1000, null=True)),
                ('in_need_of_repair', models.CharField(blank=True, max_length=1000, null=True)),
                ('spoilt_beyond_repair', models.CharField(blank=True, max_length=1000, null=True)),
                ('other_avenues', models.CharField(blank=True, max_length=1000, null=True)),
                ('list_of_recycling_locations', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReuseChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_of_reuse', models.CharField(blank=True, choices=[('DONATE', 'Donate'), ('RESELL', 'Resell'), ('REPAIR', 'Repair')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField(blank=True, null=True)),
                ('organisation_name', models.CharField(blank=True, max_length=100, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('block_number', models.CharField(blank=True, max_length=10, null=True)),
                ('street_name', models.CharField(blank=True, max_length=200, null=True)),
                ('building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('operating_hours', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('website', models.SlugField(blank=True, null=True)),
                ('categories_accepted', models.CharField(blank=True, max_length=1000, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('channel_of_reuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycleapp.reusechannel')),
            ],
        ),
    ]
