# Generated by Django 3.2 on 2022-01-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalchannel',
            name='sn',
        ),
    ]
