# Generated by Django 3.2 on 2022-01-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callforcollection',
            old_name='items_collected',
            new_name='contact_method',
        ),
        migrations.AddField(
            model_name='callforcollection',
            name='contact_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='callforcollection',
            name='minimum_weight',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='callforcollection',
            name='pricing_terms',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='callforcollection',
            name='website',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='callforcollection',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
