# Generated by Django 3.2 on 2022-01-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0002_auto_20211220_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalchannel',
            old_name='blocknumber',
            new_name='block_number',
        ),
        migrations.RenameField(
            model_name='physicalchannel',
            old_name='name_of_organisation',
            new_name='organisation_name',
        ),
        migrations.RemoveField(
            model_name='physicalchannel',
            name='category',
        ),
        migrations.AddField(
            model_name='g',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='physicalchannel',
            name='categories_accepted',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='physicalchannel',
            name='channel_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='physicalchannel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalchannel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalchannel',
            name='street_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='physicalchannel',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
