# Generated by Django 3.2 on 2022-01-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0003_alter_physicalchannel_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalchannel',
            name='channel_of_reuse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
