# Generated by Django 3.2 on 2022-01-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0003_auto_20220106_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='g',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='n',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
