# Generated by Django 3.2 on 2022-01-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0004_auto_20220106_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='n',
            name='list_of_recycling_locations',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='n',
            name='other_avenues',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
