# Generated by Django 3.2 on 2022-01-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0004_alter_physicalchannel_channel_of_reuse'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneMapRecyclingBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('block_number', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='physicalchannel',
            name='channel_of_reuse',
            field=models.CharField(blank=True, choices=[('DONATE', 'Donate'), ('RESELL', 'Resell'), ('REPAIR', 'Repair')], max_length=100, null=True),
        ),
    ]
