import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { Text, Heading, Button, Box, Flex } from '@chakra-ui/react';
import { ArrowForwardIcon } from '@chakra-ui/icons';

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Home | RecycleGoWhere</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex flexDirection="row" justifyContent="center" alignItems="center" marginBottom={10}>
        <Box>
          <Heading as="h1">Pulau Semakau will be completely filled by 2035.</Heading>
          <Heading as="h2">Let’s do what we can to stop this!</Heading>
          <Link href="/recyclegowhere" passHref>
            <Button as="a" rightIcon={<ArrowForwardIcon />}>I want to help!</Button>
          </Link>
        </Box>
        <Box>
          <Image
            src="/unclesemakau_singlet.png"
            alt="Uncle Semakau in a Singlet"
            width={787}
            height={790}
          />
        </Box>
      </Flex>
      <Box textAlign="center" p={4}>
        <Heading as="h1">What&apos;s the Issue?</Heading>
        <Text>
          By 2035, Pulau Semakau will be filled. In 20 years, plastic waste will triple from the current amount.
          Yet, Singapore’s domestic recycling rate has fallen from 17% in 2019 to 13% in 2020.
          Although 6 in 10 households recycle regularly, the lack of proper practice in handling rubbish has resulted in ineffective recycling processes.
        </Text>
      </Box>
      <Box backgroundColor="teal.400">
        <Heading as="h1">Reduce Reuse Recycle</Heading>
      </Box>
      <Box>
        <Heading as="h1">About RecycleGoWhere</Heading>
        <Text>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum, nunc eu congue bibendum, turpis ex molestie turpis, a tincidunt dolor turpis vitae augue.
          Vivamus non tempus ligula, at bibendum odio.
          Vivamus ac convallis ex, eu tincidunt nibh. Morbi quis turpis mattis mi convallis scelerisque.
        </Text>
        <Button>Start Recycling</Button>
      </Box>
      <Box>
        <Heading as="h1">Our Team</Heading>
        <Text>Insert your names here and links :D</Text>
      </Box>

    </Box >
  )
}
