import Head from 'next/head';
// import Image from 'next/image';
import Link from 'next/link';
import { Text, Heading, Button, Box, Flex, Image, Center } from '@chakra-ui/react';
import { ArrowForwardIcon } from '@chakra-ui/icons';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | RecycleGoWhere</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        {/* Hero */}
        <Flex flexDirection="row" justifyContent="center" alignItems="center" marginBottom={10}>
          <Box
            marginLeft="20px"
          >
            <Heading 
              as="h1">Pulau Semakau will be completely filled by 2035.</Heading>
            <br />
            <Heading as="h2" fontSize="lg">Let’s do what we can to stop this!</Heading>
            <br />
            <Link href="/recycle-and-reuse" passHref>
              <Button as="a" rightIcon={<ArrowForwardIcon />}>I want to help!</Button>
            </Link>
          </Box>

          <Box>
            <Image
              src="/unclesemakau_singlet.png"
              alt="Uncle Semakau in a Singlet"
              boxSize="500px"
              objectFit={"contain"}
            />
          </Box>
        </Flex>

        {/* What's the Issue */}
        <Box
          display="flex"
          borderWidth='1px' 
          borderRadius='lg' 
          overflow='hidden' 
          marginY="20px"
        >
          <Box
            flex="1"
          >
              <Image
                src="/unclesemakau.png"
                alt="Uncle Semakau in a Singlet"
                boxSize="200px"
                objectFit="contain"
                marginTop="20px"
              />
          </Box>

          <Box
            flex="3"
            padding="50px"
          >
            <Heading as="h1">What&apos;s the Issue?</Heading>
            <Text>
              By 2035, Pulau Semakau will be filled. In 20 years, plastic waste will triple from the current amount.
              Yet, Singapore’s domestic recycling rate has fallen from 17% in 2019 to 13% in 2020.
              Although 6 in 10 households recycle regularly, the lack of proper practice in handling rubbish has resulted in ineffective recycling processes.
            </Text>
          </Box>
        </Box>

        {/* About RGW */}
        <Box
          display="flex"
          borderWidth='1px' 
          borderRadius='lg' 
          overflow='hidden' 
          marginY="20px"
        >
          <Box
            flex="1"
          >
              <Image
                src="/unclesemakau.png"
                alt="Uncle Semakau in a Singlet"
                boxSize="200px"
                objectFit="contain"
                marginTop="20px"
              />
          </Box>

          <Box
            flex="3"
            padding="50px"
          >
            <Heading as="h1">About RecycleGoWhere (RGW)</Heading>
            <Text>

            </Text>

            <Button>Start Recycling</Button>
          </Box>
        </Box>

        {/* Our Team */}
        <Box
          display="flex"
          borderWidth='1px' 
          borderRadius='lg' 
          overflow='hidden' 
          marginY="20px"
        >
          <Box
            flex="1"
          >
              <Image
                src="/unclesemakau.png"
                alt="Uncle Semakau in a Singlet"
                boxSize="200px"
                objectFit="contain"
                marginTop="20px"
              />
          </Box>

          <Box
            flex="3"
            padding="50px"
          >
            <Heading as="h1">Our Team</Heading>
            <Text>

            </Text>

            <Button>Start Recycling</Button>
          </Box>
        </Box>
    </ >

  )
}
