export enum Icons {
    BABY_CHILDREN_ITEMS = "/icons/baby-children-items.png",
    BAGS_AND_ACCESSORIES = "/icons/bags-and-accessories.png",
    BOOKS = "/icons/books.png",
    CLOTHING = "/icons/clothing.png",
    CONTENT_CONTAINER = "/icons/content-container.png",
    FOOD = "/icons/food.png",
    FOOD_DRINK_CONTAINER = "/icons/food-drink-container.png",
    FURNITURE = "/icons/furniture.png",
    HOUSEHOLD_GOODS = "/icons/household-goods.png",
    ICT_EQUIPMENT = "/icons/ict-equipment.png",
    INKS_AND_TONER_CARTRIDGES = "/icons/inks-and-toner-cartridges.png",
    LAMPS = "/icons/lamps.png",
    LARGE_HOUSEHOLD_APPLIANCES = "/icons/large-household-appliances.png",
    OTHER_ELECTRICAL_APPLIANCES = "/icons/other-electrical-appliances.png",
    PAPER_AND_CARDBOARD = "/icons/paper-and-cardboard.png",
    PORTABLE_BATTERIES = "/icons/portable-batteries.png",
    RECYCLABLE = "/icons/recyclable.png",
    SHOES = "/icons/shoes.png",
    STATIONERY = "/icons/stationery.png",
    TOYS = "/icons/toys.png"
}