export enum Icons {
    BABY_CHILDREN_ITEMS = "/public/icons/baby-children-items.png",
    BAGS_AND_ACCESSORIES = "/public/icons/bags-and-accessories.png",
    BOOKS = "/public/icons/books.png",
    CLOTHING = "/public/icons/clothing.png",
    CONTENT_CONTAINER = "/public/icons/content-container.png",
    FOOD = "/public/icons/food.png",
    FOOD_DRINK_CONTAINER = "/public/icons/food-drink-container.png",
    FURNITURE = "/public/icons/furniture.png",
    HOUSEHOLD_GOODS = "/public/icons/household-goods.png",
    ICT_EQUIPMENT = "/public/icons/ict-equipment.png",
    INKS_AND_TONER_CARTRIDGES = "/public/icons/inks-and-toner-cartridges.png",
    LAMPS = "/public/icons/lamps.png",
    LARGE_HOUSEHOLD_APPLIANCES = "/public/icons/large-household-appliances.png",
    OTHER_ELECTRICAL_APPLIANCES = "/public/icons/other-electrical-appliances.png",
    PAPER_AND_CARDBOARD = "/public/icons/paper-and-cardboard.png",
    PORTABLE_BATTERIES = "/public/icons/portable-batteries.png",
    RECYCLABLE = "/public/icons/recyclable.png",
    SHOES = "/public/icons/shoes.png",
    STATIONERY = "/public/icons/stationery.png",
    TOYS = "/public/icons/toys.png"
}